/**
 * Initial mappings of Thai Company Names (Column A) to English Company Names (Column C)
 * from Google Sheets tab: Data_base
 */
export const INITIAL_COMPANY_EN_MAP: Record<string, string> = {
  "บริษัท โซลเวนตัม (ประเทศไทย) จำกัด": "Solventum (Thailand) Co., Ltd.",
  "บริษัท เอสเอ็มดี ไรส์ จำกัด (มหาชน)": "SMD Rise Public Co., Ltd.",
  "บริษัท อินโนเทค เซอร์จิคัล จำกัด": "Innotech Surgical Co., Ltd.",
  "บริษัท ซี.อาร์.เอ็ม. เฮลท์ แคร์ จำกัด": "C.R.M. Health Care Co., Ltd.",
  "บริษัท เพาเวอร์เมติค จำกัด": "Powermatic Co., Ltd.",
  "ห้างหุ้นส่วนจำกัด 3พี เมดิคอล": "3P Medical Ltd., Part.",
  "บริษัท โอลิมปัส (ประเทศไทย) จำกัด": "Olympus (Thailand) Co., Ltd.",
  "บริษัท เกทส์ เฮลธ์แคร์ (ประเทศไทย) จำกัด": "Gates Healthcare (Thailand) Co., Ltd.",
  "บริษัท ดับเบิ้ล ยู เทค จำกัด": "Double U Tech Co., Ltd.",
  "บริษัท เดรเกอร์ เมดิคัล (ประเทศไทย) จำกัด": "Dräger Medical (Thailand) Co., Ltd.",
  "บริษัท เนชั่นแนล เฮลท์แคร์ ซิสเท็มส์ จำกัด": "National Healthcare Systems Co., Ltd.",
  "บริษัท อี ฟอร์ แอล เอม จำกัด (มหาชน)": "DKSH E for L Aim Public Co., Ltd.",
  "บริษัท วีอาร์พี เดนท์ จำกัด": "VRP Dent Co., Ltd.",
  "บริษัท 3เอ็ม ประเทศไทย จำกัด": "3M Thailand Co., Ltd.",
  "บริษัท อินโนเวชั่น จำกัด": "Innovation Co., Ltd.",
  "บริษัท คาร์ล ไซส์ จำกัด": "Carl Zeiss Co., Ltd.",
  "บริษัท เดนท์สพลาย ซิโรน่า (ประเทศไทย) จำกัด": "Dentsply Sirona (Thailand) Co., Ltd.",
  "บริษัท โกสินทร์เวชภัณฑ์ จำกัด": "Kosin Vejjabhandh Co., Ltd.",
  "บริษัท แอล เอ็ม ที กรุ๊ป จำกัด": "LMT Group Co., Ltd.",
  "บริษัท เซสท์-เมด จำกัด": "Zest-Med Co., Ltd.",
  "บริษัท อาฟต้า เซอร์วิส แอนด์ ซัพพลาย จำกัด": "After Service and Supply Co., Ltd.",
  "บริษัท เมดเทค เอเชีย จำกัด": "Medtech Asia Co., Ltd.",
  "บริษัท สยาม เอสซีไอ จำกัด": "Siam SCI Co., Ltd.",
  "บริษัท โกลบอล เฮลท์ตี้ แคร์ จำกัด": "Global Healthy Care Co., Ltd.",
  "บริษัท มัตสึนากะ (ประเทศไทย) จำกัด": "Matsunaga (Thailand) Co., Ltd.",
  "บริษัท เมดิกา เฮลท์แคร์ จำกัด": "Medica Healthcare Co., Ltd.",
  "บริษัท เจเอส ยูนิเทค จำกัด": "JS Unitech Co., Ltd.",
  "บริษัท กรุงไทยเมดิคอล จำกัด": "Krungthai Medical Co., Ltd.",
  "บริษัท วี.เอ.เอนจิเนียริ่ง จำกัด": "V.A. Engineering Co., Ltd.",
  "บริษัท เลเซอร์ เอ็นจิเนีย จำกัด": "Laser Engineer Co., Ltd.",
  "บริษัท โปรเฟสชั่นแนล เซลล์ แอนด์ เซอร์วิส จำกัด": "Professional Sales and Service Co., Ltd.",
  "บริษัท มาราธอน (ประเทศไทย) จำกัด": "Marathon (Thailand) Co., Ltd.",
  "บริษัท สเปซเมด จำกัด": "Spacemed Co., Ltd.",
  "บริษัท บิงโกล จำกัด": "Bingol Co., Ltd.",
  "บริษัท บอสตัน ไซเอนทิฟิค(ประเทศไทย) จำกัด": "Boston Scientific (Thailand) Ltd.",
  "บริษัท เมตตา เมดเทค จำกัด": "Metta Medtech Co., Ltd.",
  "บริษัท เมดิคอลเลเซอร์ เทคโนโลยี่ (ประเทศไทย) จำกัด": "Medical Laser Technology (Thailand) Co., Ltd.",
  "บริษัท เจ.อี.พี.เอ็นเตอร์ไพรส์ จำกัด": "J.E.P. Enterprise Co., Ltd.",
  "บริษัท กิบไทย จำกัด": "Gibthai Co., Ltd.",
  "บริษัท เกตเวย์ เฮลท์แคร์ จำกัด": "Gateway Healthcare Co., Ltd.",
  "บริษัท เกทิงเกะ (ประเทศไทย) จำกัด": "Getinge (Thailand) Co., Ltd.",
  "บริษัท เกรียงยุทธ เอนจิเนียริ่ง จำกัด": "Kriangyuth Engineering Co., Ltd.",
  "บริษัท แกรนดี อินเตอร์เนชั่นแนล จำกัด": "Grandy International Co., Ltd.",
  "บริษัท ไกเนติค เอ็มเอ็มเอส เอ็นเตอร์ไพรส์ จำกัด": "Kinetic MMS Enterprise Co., Ltd.",
  "บริษัท ควอนตัม เฮลธ์แคร์ (ประเทศไทย) จำกัด": "Quantum Healthcare (Thailand) Co., Ltd.",
  "บริษัท คอนเนค ไดแอกโนสติกส์ จำกัด": "Connect Diagnostics Co., Ltd.",
  "บริษัท คาร์ดิแนล เฮลท์ 222 (ประเทศไทย) จำกัด": "Cardinal Health 222 (Thailand) Ltd.",
  "บริษัท เคพีไฟว์ จำกัด": "KP Five Co., Ltd.",
  "บริษัท เค เอเบิล เทค จำกัด": "K Able Tech Co., Ltd.",
  "บริษัท แคร์สตรีม เฮลธ์ (ประเทศไทย) จำกัด": "Carestream Health (Thailand) Ltd.",
  "บริษัท ไคนีติก เอ็มเอ็มเอส เอ็นเตอร์ไพรส์ จำกัด": "Kinetic MMS Enterprise Co., Ltd.",
  "บริษัท จอห์นสัน แอนด์ จอห์นสัน (ไทย) จำกัด": "Johnson & Johnson (Thai) Ltd.",
  "บริษัท จอห์นสัน เฮลธ์ เทค (ประเทศไทย) จำกัด": "Johnson Health Tech (Thailand) Co., Ltd.",
  "บริษัท จำเริญแพทย์ภัณฑ์ จำกัด": "Jamroen Medical Supplies Co., Ltd.",
  "บริษัท จิโกะ อินเตอร์เทรด จำกัด": "Jiko Intertrade Co., Ltd.",
  "บริษัท จีอี เฮลธ์แคร์ (ประเทศไทย) จำกัด": "GE Healthcare (Thailand) Co., Ltd.",
  "บริษัท เจ ซัมมิท จำกัด": "J Summit Co., Ltd.",
  "บริษัท เจพีพี แคร์ จำกัด": "JPP Care Co., Ltd.",
  "บริษัท เจเอฟ แอดวานซ์ เมด จำกัด": "JF Advance Med Co., Ltd.",
  "บริษัท ไจโก้ อินเตอร์เทรด จำกัด": "Jaiko Intertrade Co., Ltd.",
  "บริษัท ชินกฤช จำกัด": "Chinnakrit Co., Ltd.",
  "บริษัท ซิมเมอร์ ไบโอเมท (ประเทศไทย) จำกัด": "Zimmer Biomet (Thailand) Co., Ltd.",
  "บริษัท ซิลลิก ฟาร์มา จำกัด": "Zuellig Pharma Co., Ltd.",
  "บริษัท ซิสเม็กซ์ (ประเทศไทย) จำกัด": "Sysmex (Thailand) Co., Ltd.",
  "บริษัท ซีเอ็มซี ไบโอเท็ค จำกัด": "CMC Biotech Co., Ltd.",
  "บริษัท ซีเอ็มดี เฮลธ์แคร์ จำกัด": "CMD Healthcare Co., Ltd.",
  "บริษัท ซี.เอ็ม.พี.โปรดักส์ จำกัด": "C.M.P. Products Co., Ltd.",
  "บริษัท ซีแอนด์เค บิสซิเนส ดีเวลลอปเม้นท์ จำกัด": "C&K Business Development Co., Ltd.",
  "บริษัท ซีแอนด์เค เมดิคอล อินเตอร์กรุ๊ป จำกัด": "C&K Medical Intergroup Co., Ltd.",
  "บริษัท เซนต์เมด จำกัด (มหาชน)": "Saint Med Public Co., Ltd.",
  "บริษัท เซ็ปเปอร์ อินสตรูเมนท์ จำกัด": "Sepper Instrument Co., Ltd.",
  "บริษัท เซอร์เคิลไลฟ์ จำกัด": "Circle Life Co., Ltd.",
  "บริษัท โซเด็กซ์โซ่ เซอร์วิสเซส (ประเทศไทย) จำกัด": "Sodexo Services (Thailand) Ltd.",
  "บริษัท โซโนมา จำกัด": "Sonoma Co., Ltd.",
  "บริษัท โซวิค จำกัด": "Sovic Co., Ltd.",
  "บริษัท โซวี่ จำกัด": "Sowee Co., Ltd.",
  "บริษัท ไซเอนซ์ เอนจิเนียร์ อินเตอร์เนชั่นแนล จำกัด": "Science Engineer International Co., Ltd.",
  "บริษัท ดีเคเอสเอช (ประเทศไทย) จำกัด": "DKSH (Thailand) Ltd.",
  "บริษัท ดีดีเอส อินโนเทค จำกัด": "DDS Innotech Co., Ltd.",
  "บริษัท ดีเอส ออล จำกัด": "DS All Co., Ltd.",
  "บริษัท เด็กซ์ทรัส เอ็นจิเนียริ่ง จำกัด": "Dextrus Engineering Co., Ltd.",
  "บริษัท เดลต้า แลบอราตอรี่ จำกัด": "Delta Laboratory Co., Ltd.",
  "บริษัท ไดรฟ์ เด็นทัล อินคอร์ปอเรชั่น จำกัด": "Drive Dental Incorporation Co., Ltd.",
  "บริษัท ตะวันแม็คไวสซ์ จำกัด": "Tawan McWise Co., Ltd.",
  "บริษัท เตียวฮงสีลม จำกัด": "Teohong Silom Co., Ltd.",
  "บริษัท ไตร โซลูชั่น จำกัด": "Tri Solution Co., Ltd.",
  "บริษัท ทรานส์เมดิค (ประเทศไทย) จำกัด": "Transmedic (Thailand) Co., Ltd.",
  "บริษัท ทริปเปิล เอท ครีเอท จำกัด": "Triple 8 Create Co., Ltd.",
  "บริษัท ทรีต เมด จำกัด": "Treat Med Co., Ltd.",
  "บริษัท ที อี คิว จำกัด": "TEQ Co., Ltd.",
  "บริษัท เทอรูโม (ประเทศไทย) จำกัด": "Terumo (Thailand) Co., Ltd.",
  "บริษัท ไทย จีแอล จำกัด": "Thai GL Co., Ltd.",
  "บริษัท ไทยโอซูก้า จำกัด": "Thai Otsuka Co., Ltd.",
  "บริษัท ไทย ไอพี จํากัด": "Thai IP Co., Ltd.",
  "บริษัท ธเนศ ไซเอนซ์ จำกัด": "Thanet Science Co., Ltd.",
  "บริษัท นิว ไลฟ์เมด จำกัด": "New Lifemed Co., Ltd.",
  "บริษัท นิว อาย จำกัด": "New Eye Co., Ltd.",
  "บริษัท โนวาเทค เฮลธ์แคร์ จำกัด": "Novatech Healthcare Co., Ltd.",
  "บริษัท บลู แพลนเน็ต เทรดดิ้ง จำกัด": "Blue Planet Trading Co., Ltd.",
  "บริษัท บอว์เมด ยู.เค. (เอเชีย) จำกัด": "Bowmed U.K. (Asia) Co., Ltd.",
  "บริษัท บอส เมด เอนจิเนียริ่ง จำกัด": "Boss Med Engineering Co., Ltd.",
  "บริษัท บางกอก อินเตอร์คอน จำกัด": "Bangkok Intercon Co., Ltd.",
  "บริษัท บิวตี้ โซลูชั่น จำกัด": "Beauty Solution Co., Ltd.",
  "บริษัท บีเจซี เฮลท์แคร์ จำกัด": "BJC Healthcare Co., Ltd.",
  "บริษัท บีเจเอช เมดิคัล จำกัด": "BJH Medical Co., Ltd.",
  "บริษัท บีเจเอช เฮลธ์แคร์ จำกัด": "BJH Healthcare Co., Ltd.",
  "บริษัท บีดีเอช เมดิคัล ซัพพลาย จำกัด": "BDH Medical Supply Co., Ltd.",
  "บริษัท บี. บราวน์ (ประเทศไทย) จำกัด": "B. Braun (Thailand) Ltd.",
  "บริษัท เบคตัน ดิ๊กกินสัน (ประเทศไทย) จำกัด": "Becton Dickinson (Thailand) Ltd.",
  "บริษัท เบคไทย แบงค็อก อุปกรณ์และเคมีภัณฑ์ จำกัด": "BECTHAI Bangkok Equipment & Chemical Co., Ltd.",
  "บริษัท เบสท์ เวิร์ค (ประเทศไทย) จำกัด": "Best Work (Thailand) Co., Ltd.",
  "บริษัท แบ็กซ์เตอร์ เฮลธ์แคร์ (ประเทศไทย) จำกัด": "Baxter Healthcare (Thailand) Ltd.",
  "บริษัท แบงค็อก เมดิคอลส์ โปร จำกัด": "Bangkok Medicals Pro Co., Ltd.",
  "บริษัท โบว์เมด ยู.เค. (เอเชีย) จำกัด": "Bowmed U.K. (Asia) Co., Ltd.",
  "บริษัท ไบด์ ริช จำกัด": "Bide Rich Co., Ltd.",
  "บริษัท ไบเออร์ไทย จำกัด": "Bayer Thai Co., Ltd.",
  "บริษัท ไบโอเมนเทนแนนส์ เซอร์วิส แอนด์ ซัพพลาย กรุ๊ป จำกัด (สำนักงานใหญ่)": "Bio Maintenance Service and Supply Group Co., Ltd. (Head Office)",
  "บริษัท ไบโอ-ราด แลบบอราทอรี่ส์ จำกัด": "Bio-Rad Laboratories Co., Ltd.",
  "บริษัท ไบโอแอคทีฟ อินเตอร์ จำกัด": "Bioactive Inter Co., Ltd.",
  "บริษัท ป.เคมีอุปกรณ์ จำกัด": "P. Chemi Equipment Co., Ltd.",
  "บริษัท ปัญญ์สุข เมดิคัล จำกัด": "Punsuk Medical Co., Ltd.",
  "บริษัท พรอมท์ เดนทัล แอนด์ เมดิคัล ซัพพลาย จำกัด": "Prompt Dental and Medical Supply Co., Ltd.",
  "บริษัท พลัส เมดิคอล ซัพพลาย จำกัด": "Plus Medical Supply Co., Ltd.",
  "บริษัท พารากอนแคร์ (ไทยแลนด์) จำกัด": "Paragon Care (Thailand) Co., Ltd.",
  "บริษัท พาราเมาท์ เบด (ประเทศไทย) จำกัด": "Paramount Bed (Thailand) Co., Ltd.",
  "บริษัท พาวเวอร์ เฮลธ์แคร์ จำกัด": "Power Healthcare Co., Ltd.",
  "บริษัท พีอีโอ กรุ๊ป จำกัด": "PEO Group Co., Ltd.",
  "บริษัท พีเอสอี เมดิคอล จำกัด": "PSE Medical Co., Ltd.",
  "บริษัท เพาเวอร์ อินคลูด เทคโนโลยี จำกัด": "Power Include Technology Co., Ltd.",
  "บริษัท เพียว เมดิคอล พลัส จำกัด": "Pure Medical Plus Co., Ltd.",
  "บริษัท ไพซีส เมดิคอล จำกัด": "Pisces Medical Co., Ltd.",
  "บริษัท ไพรม์เมดิคอล จำกัด": "Prime Medical Co., Ltd.",
  "บริษัท ไพส์ซีส เมดิคอล จำกัด": "Pisces Medical Co., Ltd.",
  "บริษัท ไพโอเนียร์ อินเตอร์ ซัพพลาย จำกัด": "Pioneer Inter Supply Co., Ltd.",
  "บริษัท ฟอนดูซ เซอร์วิส เทคโนโลยี จำกัด": "Fondus Service Technology Co., Ltd.",
  "บริษัท ฟาร์ ทริลเลียน จำกัด": "Far Trillion Co., Ltd.",
  "บริษัท ฟิลเทค เอ็นเตอร์ไพรส์ 1994 จำกัด (มหาชน)": "Filtech Enterprise 1994 Public Co., Ltd.",
  "บริษัท ฟิลิปส์ (ประเทศไทย) จำกัด": "Philips (Thailand) Ltd.",
  "บริษัท ฟิวเจอร์ เมดิคอล ซัพพลาย จำกัด": "Future Medical Supply Co., Ltd.",
  "บริษัท ฟูจิฟิล์ม (ประเทศไทย) จำกัด": "Fujifilm (Thailand) Ltd.",
  "บริษัท มะรุงโรจน์ จำกัด": "Marungroj Co., Ltd.",
  "บริษัท มัฟฟิน จำกัด": "Muffin Co., Ltd.",
  "บริษัท มายด์ เมดิคอล แคร์ จำกัด": "Mind Medical Care Co., Ltd.",
  "บริษัท มาร์ธา กรุ๊ป จำกัด": "Martha Group Co., Ltd.",
  "บริษัท มารุ่งโรจน์ จำกัด": "Marungroj Co., Ltd.",
  "บริษัท มิตรการแพทย์ จำกัด": "Mitkarnpaet Co., Ltd.",
  "บริษัท เมกะฟิล จำกัด": "Megafill Co., Ltd.",
  "บริษัท เมดดิคอล แอพไพลแอนซ์ เซ็นเตอร์ จำกัด": "Medical Appliance Center Co., Ltd.",
  "บริษัท เมดโทรนิค (ประเทศไทย) จำกัด": "Medtronic (Thailand) Ltd.",
  "บริษัท เมดโฟกัส จำกัด": "Medfocus Co., Ltd.",
  "บริษัท เมด วัน จำกัด": "Med One Co., Ltd.",
  "บริษัท เมดิคัล แอพพลายแอนซ์ เซ็นเตอร์ จำกัด": "Medical Appliance Center Co., Ltd.",
  "บริษัท เมดิคูล จำกัด": "Medicool Co., Ltd.",
  "บริษัท เมดิแคร์ (ประเทศไทย) จำกัด": "Medicare (Thailand) Co., Ltd.",
  "บริษัท เมดิทอป จำกัด": "Meditop Co., Ltd.",
  "บริษัท เมโทรซิสเต็มส์คอร์ปอเรชั่น จำกัด (มหาชน)": "Metro Systems Corporation Public Co., Ltd.",
  "บริษัท ยูนิเทค เฮลธ์แคร์ จำกัด": "Unitech Healthcare Co., Ltd.",
  "บริษัท ยูนิไทย กรุ๊ป จำกัด": "Unithai Group Co., Ltd.",
  "บริษัท ยูนิเวอร์แซลควอลลิตี้ จำกัด": "Universal Quality Co., Ltd.",
  "บริษัท ยู.พี.เมดิคอล ซอลเตอร์ จำกัด": "U.P. Medical Salter Co., Ltd.",
  "บริษัท ยูแฟม คลินิก จำกัด": "Ufam Clinic Co., Ltd.",
  "บริษัท ยูโรสแกน จำกัด": "Euroscan Co., Ltd.",
  "บริษัท ลันดาล (ไทยแลนด์) จำกัด": "Lundal (Thailand) Co., Ltd.",
  "บริษัท ลิวาโนวา (ประเทศไทย) จำกัด": "LivaNova (Thailand) Co., Ltd.",
  "บริษัท เลเซอร์เมด จำกัด": "Lasermed Co., Ltd.",
  "บริษัท แล็บ ลีดเดอร์ จำกัด": "Lab Leader Co., Ltd.",
  "บริษัท วัน ฮันเดรด เมดิคอล จำกัด": "One Hundred Medical Co., Ltd.",
  "บริษัท วานิช เมดิคัล จำกัด": "Vanich Medical Co., Ltd.",
  "บริษัท วาเลอร์ เฮลธ์ จำกัด": "Valor Health Co., Ltd.",
  "บริษัท วิคตอรี่ ครุภัณฑ์การแพทย์ จำกัด": "Victory Medical Equipment Co., Ltd.",
  "บริษัท วีณา สปอร์ต อินเตอร์เทรด จำกัด": "Vina Sport Intertrade Co., Ltd.",
  "บริษัท เวิลด์ เมด อิควิปเม้นท์ จำกัด": "World Med Equipment Co., Ltd.",
  "บริษัท เวิลด์ เมดิคอล จำกัด": "World Medical Co., Ltd.",
  "บริษัท ศัลยเวช จำกัด": "Salyavej Co., Ltd.",
  "บริษัท สกายเด็นท์ จำกัด": "Skydent Co., Ltd.",
  "บริษัท สตรอแมน กรุ๊ป (ประเทศไทย) จำกัด": "Straumann Group (Thailand) Co., Ltd.",
  "บริษัท สตรอแมนน์ กรุ๊ป (ประเทศไทย) จำกัด": "Straumann Group (Thailand) Co., Ltd.",
  "บริษัท สตาร์ อิเล็กทรอนิกส์ เซลส์ แอนด์ เซอร์วิส จำกัด": "Star Electronics Sales and Service Co., Ltd.",
  "บริษัท สไตรเกอร์ (ประเทศไทย) จำกัด": "Stryker (Thailand) Ltd.",
  "บริษัท สปีด เมดิคอล จำกัด (สำนักงานใหญ่)": "Speed Medical Co., Ltd. (Head Office)",
  "บริษัท สมาร์ท เทคโนโลยี แอนด์ โปรดักส์ จำกัด": "Smart Technology and Products Co., Ltd.",
  "บริษัท สมิท เมดิคัล จำกัด": "Smith Medical Co., Ltd.",
  "บริษัท สมิท แอนด์ เนฟฟิว จำกัด": "Smith & Nephew Co., Ltd.",
  "บริษัท สยามเทค อิควิปเม้นท์ จำกัด": "Siamtech Equipment Co., Ltd.",
  "บริษัท สยาม นิสซิน จำกัด": "Siam Nissin Co., Ltd.",
  "บริษัท สยาม อินเตอร์ เนชั่นแนล เมดิคัล อิควิปเม้นท์ จำกัด": "Siam International Medical Equipment Co., Ltd.",
  "บริษัท สยาม ฮอสพิทอล ซัพพลาย จำกัด": "Siam Hospital Supply Co., Ltd.",
  "บริษัท สิงห์ คอร์เปอเรชั่น จำกัด": "Sing Corporation Co., Ltd.",
  "บริษัท ออดิเมด จำกัด": "Audimed Co., Ltd.",
  "บริษัท ออมนิเมด จำกัด": "Omnimed Co., Ltd.",
  "บริษัท ออริจินเนเตอร์ จำกัด": "Originator Co., Ltd.",
  "บริษัท ออลล์เวล ไลฟ์ จำกัด": "Allwell Life Co., Ltd.",
  "บริษัท อะไลน เทคโนโลยี (ประเทศไทย) จำกัด": "Align Technology (Thailand) Co., Ltd.",
  "บริษัท อัลคอน แลบอราทอรีส์ (ประเทศไทย) จำกัด": "Alcon Laboratories (Thailand) Ltd.",
  "บริษัท อาทิตย์ ครุภัณฑ์การแพทย์ จำกัด": "Athit Medical Equipment Co., Ltd.",
  "บริษัท อินเตอร์ ฟาร์มา จำกัด (มหาชน)": "Inter Pharma Public Co., Ltd.",
  "บริษัท อินเตอร์ ฟาร์มา เมดเทค จำกัด": "Inter Pharma Medtech Co., Ltd.",
  "บริษัท อินทิเกรทเต็ด เมดิคอล เซอร์วิส จำกัด": "Integrated Medical Service Co., Ltd.",
  "บริษัท อินไทม์ เมดิคอล จำกัด": "Intime Medical Co., Ltd.",
  "บริษัท อินโนเวทีฟ อิมเมจจิ้ง ซิสเต็มส์ จำกัด": "Innovative Imaging Systems Co., Ltd.",
  "บริษัท อิน บอดี้ (ไทยแลนด์) จำกัด": "InBody (Thailand) Co., Ltd.",
  "บริษัท อีโนเวชั่นส์ จำกัด": "Enovations Co., Ltd.",
  "บริษัท อุดมเมดิคอล อิควิปเม้นท์ จำกัด": "Udom Medical Equipment Co., Ltd.",
  "บริษัท เอชพี อิงค์ (ประเทศไทย) จำกัด": "HP Inc. (Thailand) Ltd.",
  "บริษัท เอเซีย แปซิฟิค ปิโตรเคมิคอล จำกัด": "Asia Pacific Petrochemical Co., Ltd.",
  "บริษัท เอทีแซด โกลบอล จำกัด": "ATZ Global Co., Ltd.",
  "บริษัท เอ็นโดเลนส์ จำกัด": "Endolens Co., Ltd.",
  "บริษัท เอนเอสพี โซลูชั่นส์ จำกัด": "NSP Solutions Co., Ltd.",
  "บริษัท เอ็มดี เฮลท์แคร์ จำกัด": "MD Healthcare Co., Ltd.",
  "บริษัท เอ็มพี กรุ๊ป (ประเทศไทย) จำกัด": "MP Group (Thailand) Co., Ltd.",
  "บริษัท เอ็ม.ไอ.แคลลิเบรชั่น ซิสเท็ม จำกัด": "M.I. Calibration System Co., Ltd.",
  "บริษัท เอเมอร์สัน กรุ๊ป จำกัด": "Emerson Group Co., Ltd.",
  "บริษัท เอราวัณ ไฮเทค จำกัด": "Erawan Hi-Tech Co., Ltd.",
  "บริษัท เอส เค ที ซิสเท็ม แอนด์ เดคคอเรชั่น จำกัด": "SKT System and Decoration Co., Ltd.",
  "บริษัท เอสโค่ (ไทยแลนด์) จำกัด": "Esco (Thailand) Co., Ltd.",
  "บริษัท เอส.ดี. ทันตเวช 1988 จำกัด": "S.D. Tantavej 1988 Co., Ltd.",
  "บริษัท เอสทีพี คอร์ปอเรชั่น จำกัด": "STP Corporation Co., Ltd.",
  "บริษัท เอสทีแอล คอนสตรัคชั่น อีควิปเม้นท์ จำกัด": "STL Construction Equipment Co., Ltd.",
  "บริษัท เอสอาร์เอส แม็กซ์พลัส จำกัด": "SRS Max Plus Co., Ltd.",
  "บริษัท เอสเอ็มเคที (ประเทศไทย) จำกัด": "SMKT (Thailand) Co., Ltd.",
  "บริษัท เอส.เอ็ม.เจ. อินเตอร์ โปรดักส์ จำกัด": "S.M.J. Inter Products Co., Ltd.",
  "บริษัท เอสเอ็มดี คอนเน็กซ์ จำกัด": "SMD Connex Co., Ltd.",
  "บริษัท เอสเอ็มดี เจเนซิส จำกัด": "SMD Genesis Co., Ltd.",
  "บริษัท เอสแอล เบสท์ ทรานสปอร์ต จำกัด": "SL Best Transport Co., Ltd.",
  "บริษัท เอแอลที เทเลคอม จำกัด (มหาชน)": "ALT Telecom Public Co., Ltd.",
  "บริษัท เอไอซี เฮลธ์แคร์ จำกัด": "AIC Healthcare Co., Ltd.",
  "บริษัท เอิร์ธไลน์ จำกัด": "Earthline Co., Ltd.",
  "บริษัท แอคคอร์ด คอร์ปอเรชั่น จำกัด": "Accord Corporation Co., Ltd.",
  "บริษัท แอ๊คเตออน (ประเทศไทย) จำกัด": "Acteon (Thailand) Co., Ltd.",
  "บริษัท แอตลาส คอปโก้ (ประเทศไทย) จำกัด": "Atlas Copco (Thailand) Ltd.",
  "บริษัท แอ๊บบอต ลาบอแรตอรีส จำกัด": "Abbott Laboratories Ltd.",
  "บริษัท แอร์ ลิควิด (ประเทศไทย) จำกัด": "Air Liquide (Thailand) Ltd.",
  "บริษัท แอลบีเอส ไลฟ์ จำกัด": "LBS Life Co., Ltd.",
  "บริษัท แอสตราโก เมดิเคิล เน็ตเวิร์คส จำกัด": "Astrago Medical Networks Co., Ltd.",
  "บริษัท โอเชี่ยนเมด จำกัด": "Oceanmed Co., Ltd.",
  "บริษัท ไอดีลเวล จำกัด": "Idealwell Co., Ltd.",
  "บริษัท ไอดีเอ็มเอส จำกัด": "IDMS Co., Ltd.",
  "บริษัท ไอดีเอส เมดิคอล ซิสเต็มส์ (ประเทศไทย) จำกัด": "IDS Medical Systems (Thailand) Ltd.",
  "บริษัท ไอโวคลาร์ วีวาเดนท์ (ประเทศไทย) จำกัด": "Ivoclar Vivadent (Thailand) Ltd.",
  "บริษัท ฮอซลิงค์ เมดิคัล จำกัด": "Hoslink Medical Co., Ltd.",
  "บริษัท ฮอลลีวู้ด อินเตอร์เนชั่นแนล จำกัด": "Hollywood International Co., Ltd.",
  "บริษัท เฮาเซ่น-เบิร์นสไตน์ จำกัด": "Hausen-Bernstein Co., Ltd.",
  "บริษัท แฮนด์พีซ โซลูชั่นส์ จำกัด": "Handpiece Solutions Co., Ltd.",
  "บริษัท ไฮเปอร์บาริก เทคโนโลยี จำกัด": "Hyperbaric Technology Co., Ltd.",
  "สมาคมส่งเสริมเทคโนโลยี (ไทย-ญี่ปุ่น)": "Technology Promotion Association (Thailand-Japan)",
  "ห้างหุ้นส่วนจำกัด ที แอนด์ อาร์ ซัพพลาย ทูลส์": "T&R Supply Tools Ltd., Part.",
  "ห้างหุ้นส่วนจำกัด สหไทย กรุ๊ป พลัส": "Sahathai Group Plus Ltd., Part.",
  "ห้างหุ้นส่วนจำกัด เอทู พลัส": "A2 Plus Ltd., Part.",
  "อื่นๆ": "Others"
};
